### PR TITLE
texture mapping fix

### PR DESCRIPTION
**Pull request by tobyplowy**

### CODE REVIEW

**Comment by tobyplowy** [comment]
@D00Med this shuld fix the texture mapping on the x shaped pannels in the midle the texture was upside down

**Comment by tobyplowy** [comment]
@D00Med sorry for not including this in the other one XD

**Comment by D00Med** [comment]
No problem

**Comment by D00Med** [comment]
and thanks

**Comment by tobyplowy** [comment]
@D00Med no problem have a good night

**Comment by tobyplowy** [comment]
'night

**Pull request merged**
