### PR TITLE
leaf flikering fix

### PR DESCRIPTION
**Pull request by tobyplowy**
this will fix all leaf flikkering

### CODE REVIEW

**Comment by D00Med** [comment]
Really? how does it fix it?

**Comment by tobyplowy** [comment]
@D00Med the block sides were still flikkering and now its fixed

**Comment by tobyplowy** [comment]
@D00Med also your late XD

**Comment by tobyplowy** [comment]
@D00Med Take a look

Also Thank you for learning me how to work with github Without You Learning Me This pull would not be possible

**Comment by D00Med** [comment]
Ok, great.
Yeah, not going to stick around, too tired for minetest.
I will have a look. You're welcome.

**Comment by D00Med** [comment]
Ok, great.
Yeah, not going to stick around, too tired for minetest.
I will have a look. You're welcome.

**Comment by D00Med** [comment]
Thanks for this, and also bye for now

**Pull request merged**
