### PR TITLE
Changes to leaf model

### PR DESCRIPTION
**Pull request by NathanSalapat**
I removed the double faces that were on the cross parts of the leaves, as the texture shows from both sides of the face in Minetest. This might also bring a slight speed increase, not sure. I also slightly rotated the X part of the model on the X, Y, and Z axis so the faces never run directly inside of each other when on a tree.

I also scaled the model down to half the size so all the code for the visual scale was removed as it was no longer needed. I didn't do anything with the cacti or waterlilies as I didn't have the blend available for those, and I haven't heard of any issues with that causing flickering or anything.

### CODE REVIEW

**Comment by D00Med** [comment]
I am going to test it out now.
The double faces had a purpose, they are there so that they can be seen from both sides.

**Comment by D00Med** [comment]
I think it is improved, but it's still flickering.

**Comment by NathanSalapat** [comment]
As far as I could tell the face can be seen from both sides. Using daily build of minetest. I didn't see any flickering, could you possibly take a picture? I'm wondering if it isn't from the cube, as those I didn't touch, and they probably are close to an exact match.

**Comment by NathanSalapat** [comment]
I took a closer look, the flickering is from the faces of the cube. The inner cube could be made a tiny bit smaller to reduce that flickering. I'm not sure how the normal leaves don't flicker like that, Minetest the engine, must somehow do something special for the leaves...

**Comment by D00Med** [comment]
Ok, maybe it just doesn't show on both sides for entities. I can't really take a screenshot since it's a moving thing. Ok then, I will try that.

**Comment by NathanSalapat** [comment]
Yes, entities don't show double sided, not sure why, but I've seen that happening with alpha textures. I think a solid texture on an entity shows on both sides, but not positive.

**Comment by D00Med** [comment]
>a solid texture on an entity shows on both sides, but not positive.

I've never got it to work. Is it possible to have transparency for nodes?

**Comment by NathanSalapat** [comment]
Transparency for nodes, I guess I don't understand, you have transparency on the leaves right now. Or do you mean partial transparency?

**Comment by D00Med** [comment]
Partial transparency, and I know it's a bit offtopic.

**Comment by NathanSalapat** [comment]
Partial transparency, kinda works, kinda hacky, from what I remember. I'd check out abriglass to see how it is done there. That's the only mod that really comes to mind that uses it.

**Comment by D00Med** [comment]
I thought that used nodeboxes.
I think there's a fish tank in the homedecor modpack that has transparency.

**Comment by NathanSalapat** [comment]
Good point, those were full nodes, so that might be different than a mesh.

**Comment by D00Med** [comment]
Yeah, I've done that with nodeboxes before.
More on topic, I've noticed that sometimes planes appear really dark if meshes are used(like the lily flower), do you know how to avoid this?

**Comment by NathanSalapat** [comment]
That is an engine problem, I think Sofar or Paramat have been working on that, and trying to get the lighting to be a little better for meshes and nodeboxes. Right now there isn't anything I know of that can make a difference.

**Comment by D00Med** [comment]
Ok thanks

**Pull request merged**
